### ISSUE TITLE
Code mess and complex bindings within object definitions

### ISSUE THREAD

**Issue by radek2s** [radek2s/KarcioszkiGame#31]
**Describe the bug**
1. Backend refactoring
Karcioszki UI is tightly connected with Java classes but it should not. During the adding just a one new parameter to Player object in TypeScript I'had to change this object definition also in core Java domain class. That is code smell that indicates that there "Change prevents" and I had to made an "Shotgun surgery" to change just this one small pice of code. What is more that casuse the database errors due to new field in just Runtime Object.  

Solution?
Do a refactor of Java and Angular code to provide a DTO classes that will not change the Database structure but allow frontend application to add some new extra functionality. 

2. Websocket refactoring
The web socket is a TypeScript class that receives a component as the parameter to the constructor. In that way we are creating and multiply the websocket connections because each component that want to use this feature must be registered to that class. It is also making the coupling withing pure classes and logic components. 
![image](https://user-images.githubusercontent.com/22638815/145064021-72814720-4de2-4cb4-a683-0fabe95a777c.png)

Solution? 
Web socket should be an service that has a method where user can subscribe to specific topic and unsubscribe when he wants. 

3. Naming problems
Many components has very similar naming so sometimes it can be misleading. 

Solution?
Refactor the object names.

**Comment by mdebowska** [comment]
There are still bugs like:
  
- [x] [Mobilne] na małym ekranie przy dodawaniu nazwy karty najeżdża napis Add Card
![image](https://user-images.githubusercontent.com/26547841/146972198-ab33e7e9-1762-445a-8d03-a89c4054af22.png)
- [x] Przy chęci edycji paczki w komunikacie jest password a nie PIN
- [x] nie ma obrazka kłódki dla paczki prywatnej (w ramach tego zmiana założeń - kłódka jako domyślny obrazek dla paczki prywatnej, a nie nadpisujący go)
- [x] po wpisaniu złego pinu brak informacji o czymkolwiek
- [x] [Mobilne] rozjechana strona główna
![image](https://user-images.githubusercontent.com/26547841/146973117-fe462070-558f-4243-91f5-d9da7387c598.png)
![image](https://user-images.githubusercontent.com/26547841/146973620-9e8f6952-eea7-4365-af17-42d61a6021e0.png)
Poprawić na: ![image](https://user-images.githubusercontent.com/26547841/146975475-dc9c26c6-d83a-4447-ac2e-d7c2471f87f8.png)
- [x] brak komunikatów walidacji (tworzenie gry bez nazwy)
- [x] brak marginesów
![image](https://user-images.githubusercontent.com/26547841/146973974-dac613f1-7015-4f3d-ae55-cda8b6c310a0.png)
- [x] brak przełączenia teamu po kliknięciu w szarą kartę
